### ISSUE TITLE
Can (should?) we use font-rs?

### ISSUE THREAD

**Issue by lthms** [GreenPix/sarosa#8]
Hi.

I know @Nemikolh has been struggling with font rendering from a while, so when I saw the [font-rs blogpost](https://medium.com/@raphlinus/inside-the-fastest-font-renderer-in-the-world-75ae5270c445#.pwqn7gvkq), I was wondering if we could use it?

Maybe there is no need, because @Nemikolh has already fixed all its issues, but in case he has not…

**Comment by Nemikolh** [comment]
Oh that would be awesome, but I haven't fixed all the issues regarding font rendering! : D It's too complex for me.

You proposition, is a very good idea. Ideally, we would use `oil` and `oil` would use it. But we could also start by some quick and dirty solution in `sarosa` first.

When I have some time to work on `oil`, I'll finish the language changes and investigate the integration `font-rs` for text rendering.

**Comment by lthms** [comment]
Great! Should I close this issue then and open a new one in Oil repo?

**Comment by Nemikolh** [comment]
Yes, let's do this!
